[package]
name = "fssota"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
crossterm = "0.28.1"
local-ip-address = "0.6.2"
rand = "0.8.5"
serde = "1.0.210"
serde_derive = "1.0.210"
serde_json = "1.0.128"
whoami = "1.5.2"


[[bin]]
name = "server"

[[bin]]
name = "client"
